# CircleCI configuration file
# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  main:
    jobs:
      - build:
          context:
            - DockerHub

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          make auth build push
