apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nginx-depl.yaml

# transformers
commonAnnotations:
  author: rwatkins
  source: github.com/gnomesoftuk/nginx-demo
generatorOptions:
  immutable: true
labels:
- includeSelectors: true
  pairs:
    app: nginx-demo

# rewrite and check this in to update images
images:
- name: gnomesoft/nginx-demo
  digest: sha256:6a821e5afe39e737ec09f9a56ca88b81e69528f99eda8f424df4ce6fc490420d